spring.application.name=bulkEmailArchitecture



# ===============================
# REDIS BASIC CONFIG
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379



#Rabbit MQ

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.prefetch=5

# Timeout (ms)
spring.data.redis.timeout=60000

# ===============================
# CACHE CONFIG
# ===============================
spring.cache.type=redis


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=www.faiyaz619@gmail.com
spring.mail.password=bjtv ckav pygm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true